# Generated by Django 5.2.1 on 2025-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_message_roomjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
